### ISSUE TITLE
_template function has error

### ISSUE THREAD

**Issue by Punk-UnDeaD** [bdelespierre/php-underscore#2]
```
- return Underscore::template($templateString, $data=[], $settings=[]); // bug!
+ return Underscore::template($templateString, $data, $settings);
```

**Comment by bdelespierre** [comment]
can you describe the context of this bug ? (sorry for the late response)

**Comment by Punk-UnDeaD** [comment]
see my pull request
https://github.com/bdelespierre/underscore.php/pull/3

**Comment by bdelespierre** [comment]
Fixed in PR https://github.com/bdelespierre/underscore.php/pull/4
