### ISSUE TITLE
Create a new stable version to use with production items in composer.

### ISSUE THREAD

**Issue by sebathi** [bdelespierre/php-underscore#8]

**Comment by sebathi** [comment]
Hello? This is needed for production applications :(

**Comment by bdelespierre** [comment]
Hello, you can use Underscore.php with composer by adding this to your composer.json:

``` JSON
{
    "require": {
        "bdelespierre/underscore": "^0.2.0"
    }
}
```

You can find more information about the package on [packagist](https://packagist.org/packages/bdelespierre/underscore).

If you feel it's not ready for production or think about some changes to make, feel free to file an issue or contribute by writing your own pull-request, I'll review it when I can.

The fact is this lib is not very popular amongst PHP users and I lack feedback to make further improvements. I'd appreciate any help on this matter :smile: 

Although I hope it will be useful for your project :+1:
